# Generated by Django 5.0.4 on 2024-05-02 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MMoRPGapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MMoRPGapp.responce'),
        ),
    ]
