# Generated by Django 5.0.4 on 2024-05-06 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MMoRPGapp', '0002_alter_response_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='post',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='MMoRPGapp.advert'),
        ),
    ]
