# Generated by Django 5.0.4 on 2024-05-06 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MMoRPGapp', '0005_remove_advert_response_alter_advert_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author_post', to='MMoRPGapp.response'),
        ),
    ]
